services:
  postgres:
    image: ankane/pgvector:v0.5.0
    ports:
      - "5556:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    volumes:
      - vectordata:/var/lib/postgresql/data

volumes:
  vectordata: